"""create lead model

Revision ID: 02d3cf85f4bb
Revises: 664ac26ebd72
Create Date: 2026-05-23 00:09:23.649340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02d3cf85f4bb'
down_revision: Union[str, Sequence[str], None] = '664ac26ebd72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('endereco', sa.String(), nullable=True),
    sa.Column('qtd_carros', sa.Integer(), nullable=False),
    sa.Column('qtd_caminhoes', sa.Integer(), nullable=False),
    sa.Column('eventos_pedagio_por_veiculo', sa.Integer(), nullable=False),
    sa.Column('eventos_estacionamento_por_veiculo', sa.Integer(), nullable=False),
    sa.Column('economia_co2_kg', sa.Float(), nullable=False),
    sa.Column('economia_gasolina_litros', sa.Float(), nullable=False),
    sa.Column('economia_tempo_minutos', sa.Float(), nullable=False),
    sa.Column('dinheiro_economizado', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_created_at'), 'leads', ['created_at'], unique=False)
    op.create_index(op.f('ix_leads_email'), 'leads', ['email'], unique=False)
    op.create_index(op.f('ix_leads_id'), 'leads', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leads_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_email'), table_name='leads')
    op.drop_index(op.f('ix_leads_created_at'), table_name='leads')
    op.drop_table('leads')
    # ### end Alembic commands ###
