"""alter lead events columns

Revision ID: 5e9607146fc7
Revises: 02d3cf85f4bb
Create Date: 2026-05-23 00:22:08.196989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e9607146fc7'
down_revision: Union[str, Sequence[str], None] = '02d3cf85f4bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('eventos_pedagio_carros', sa.Integer(), nullable=False))
    op.add_column('leads', sa.Column('eventos_estacionamento_carros', sa.Integer(), nullable=False))
    op.add_column('leads', sa.Column('eventos_pedagio_caminhoes', sa.Integer(), nullable=False))
    op.add_column('leads', sa.Column('eventos_estacionamento_caminhoes', sa.Integer(), nullable=False))
    op.drop_column('leads', 'eventos_estacionamento_por_veiculo')
    op.drop_column('leads', 'eventos_pedagio_por_veiculo')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('eventos_pedagio_por_veiculo', sa.INTEGER(), nullable=False))
    op.add_column('leads', sa.Column('eventos_estacionamento_por_veiculo', sa.INTEGER(), nullable=False))
    op.drop_column('leads', 'eventos_estacionamento_caminhoes')
    op.drop_column('leads', 'eventos_pedagio_caminhoes')
    op.drop_column('leads', 'eventos_estacionamento_carros')
    op.drop_column('leads', 'eventos_pedagio_carros')
    # ### end Alembic commands ###
