"""add created_at to event

Revision ID: 664ac26ebd72
Revises: ce2b074ef45d
Create Date: 2026-05-08 21:41:33.594417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '664ac26ebd72'
down_revision: Union[str, Sequence[str], None] = 'ce2b074ef45d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_events_created_at'), 'events', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_created_at'), table_name='events')
    op.drop_column('events', 'created_at')
    # ### end Alembic commands ###
